taco:
  orders:
    page-size: 10

logging:
  level:
    taco: DEBUG
spring:  datasource: 
    url: jdbc:mysql://localhost:3306/tacocloud
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema:    - classpath:schema.sql
    data:    - classpath:data.sql
    initialization-mode: always

server:  port: 8443  ssl:    key-store: classpath:mykeys.jks
    key-store-password: letmain
    key-password: letmain
---
spring:  profiles: prod
  datasource:    url: jdbc:mysql://localhost/tacocloud    name: 
    password: root
logging:
  level:
    taco: WARN